sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  alioss:
    endpoint: cn-beijing.oss.aliyuncs.com
    access-key-id: LTAI5tPVVSpTGdNstt8hyv4Y
    access-key-secret: VkXBxKRoq68o4MzyhRzH7Fa6iYG1XJ
    bucket-name: sky-toke
  redis:
    host: localhost
    port: 6379
    password: 111111
    database: 1
